### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#78]
search works only with

```
query=*
```

or similar (i.e. "*: *")

and even with wildcard the results of a search seem incomplete...

**Comment by ghost** [comment]
Ok, I've just tested this with the user you described. Currently you need to put a "*" in front of the query and after it. I'll put this into the core, so you don't need to do that.

**Comment by fetzig** [comment]
not true. doesn't work.

i.e. 
- index.html is "indexed" when the backup is created (see backup job log).
- rest api search doesn't find any string from index.html

and as already mentioned:
- result when searching for "*" seems incomplete anyways
- searching for "*" shouldn't be possible

**Comment by fetzig** [comment]
your last commit is most likely incomplete. depending on how the search should work:

when searching for "testing test" the search only finds items with "testing test". and not those with i.e. "testing" in it.

so instead of adding a wildcard at the beginning and end of the search-query. it should add the wildcard at begin and end of all words within the search-query.

**Comment by ghost** [comment]
Yes, you are right.
You also pointed out, that some files are missing. This seems to be related to a bug within the IndexAction-Plugin (some files don't get indexed). I've just taken a look at the logfile. Yet again the parser error for invalid date formats:

```
Pushing to ES index...STATUS: org.elasticsearch.index.mapper.MapperParsingException: Failed to parse [modified]
```

This is the error described within #73

**Comment by ghost** [comment]
To implement a basic version frontend version of the "backup search", simply use "_:_" as the query parameter for now.

**Comment by rsimon** [comment]
#78 broke the build - the unit tests don't pass any more (there are three files named 'creative-commons.SOME-EXTENSION, and the test search "creative-commons" now returns 0 results).

Asterisks are the wrong way to handle this, as "infix" search is already supported (see unit test). What you are looking for is either an OR query:

testing OR test

or special handling on our side, so that each keyword in the user query is handled as a separate term (i.e. serverside translation of "testing test" into "testing OR test"

I'm reverting the asterisk change and will be adding the latter solution with the next commit.

**Comment by WolfgangEibner** [comment]
I think per default search adds "AND" between two words now if no other keyword is given. Can we close this issue?

**Comment by rsimon** [comment]
Current behavior is OR (see comments + commit).
